import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

    osieciSidebar: [{ type: 'autogenerated', dirName: 'o-sieci' }],
    komunikacjaSidebar: [
      { type: 'autogenerated', dirName: 'komunikacja/dostepne-dokumenty' },
      { type: 'autogenerated', dirName: 'komunikacja/komunikacja-bezposrednia' },
      { type: 'autogenerated', dirName: 'komunikacja/komunikacja-masowa' },
      {
        type: 'category',
        label: 'Przegląd załączników',
        link: {
          type: 'generated-index',
          title: 'Program przeglądu i zarządzania dokumentami udostępnionymi w serwisach internetowych',
          description: 'Zestaw dokumentów dotyczących modelu przeglądu, oceny, klasyfikacji, naprawy, archiwizacji i usuwania dokumentów pozostających w publicznym obiegu informacyjnym podmiotu publicznego.',
        },
        items: [
          {
            type: 'category',
            label: 'Przegląd i zarządzanie dokumentami',
            items: [
              'komunikacja/przeglad-zalacznikow/przeglad-naprawa-zalacznikow-zalecenie',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-podstawy',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-slownik-pojec',
            ],
          },
          {
            type: 'category',
            label: 'Modele',
            items: [
              'komunikacja/przeglad-zalacznikow/zalecenie-07-charakter',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-model-dzialania',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-mapa-odpowiedzialnosci',
            ],
          },
          {
            type: 'category',
            label: 'Procedury',
            items: [
              'komunikacja/przeglad-zalacznikow/zalecenie-07-procedura-duze',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-procedura-male',
            ],
          },
          {
            type: 'category',
            label: 'Narzędzia i załączniki',
            items: [
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-formularz',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-rejestr',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-niezbednosc',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-decyzje',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-archiwizacja',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-przyklady',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-standard',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-lista-kontrolna',
              'komunikacja/przeglad-zalacznikow/zalecenie-07-zalacznik-schemat',
            ],
          },
        ],
      },
      { type: 'autogenerated', dirName: 'komunikacja/wymiar-komunikacja' },
    ],
    cykltikSidebar: [{ type: 'autogenerated', dirName: 'cykltik' }],
    wiedzaSidebar: [{ type: 'autogenerated', dirName: 'wiedza' }],
    kulturaSidebar: [{ type: 'autogenerated', dirName: 'kultura' }],
    pracownicySidebar: [{ type: 'autogenerated', dirName: 'pracownicy' }],
    zaopatrzenieSidebar: [{ type: 'autogenerated', dirName: 'zaopatrzenie' }],
    wsparcieSidebar: [{ type: 'autogenerated', dirName: 'wsparcie' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
