import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

    osieciSidebar: [{ type: 'autogenerated', dirName: 'o-sieci' }],
    komunikacjaSidebar: [
      { type: 'autogenerated', dirName: 'komunikacja/wymiar-komunikacja' },
      { type: 'autogenerated', dirName: 'komunikacja/dostepne-dokumenty' },
      {
        type: 'category',
        label: 'Treści od innych podmiotów',
        link: {
          type: 'generated-index',
        },
        items: [
          'komunikacja/tresci-od-innych-podmiotow/tresci-od-innych-podmiotow',
          {
            type: 'category',
            label: 'Modele',
            link: {
              type: 'doc',
              id: 'komunikacja/tresci-od-innych-podmiotow/modele-index',
            },
            items: [
              'komunikacja/tresci-od-innych-podmiotow/model-operacyjny-publikowania-tresci',
              'komunikacja/tresci-od-innych-podmiotow/model-dla-duzych-podmiotow',
              'komunikacja/tresci-od-innych-podmiotow/model-dla-malych-podmiotow',
              'komunikacja/tresci-od-innych-podmiotow/mapa-odpowiedzialnosci',
            ],
          },
          {
            type: 'category',
            label: 'Zasady i klasyfikacja',
            items: [
              'komunikacja/tresci-od-innych-podmiotow/klasyfikacja-tresci-abcd',
              'komunikacja/tresci-od-innych-podmiotow/zasady-publikacji',
              'komunikacja/tresci-od-innych-podmiotow/zakaz-domniemania-wylaczenia',
              'komunikacja/tresci-od-innych-podmiotow/obsluga-zadan-dostepnosci',
              'komunikacja/tresci-od-innych-podmiotow/procedura-brakow',
            ],
          },
          {
            type: 'category',
            label: 'Wymagania',
            link: {
              type: 'doc',
              id: 'komunikacja/tresci-od-innych-podmiotow/wymagania-index',
            },
            items: [
              'komunikacja/tresci-od-innych-podmiotow/minimalne-wymagania-przed-publikacja',
              'komunikacja/tresci-od-innych-podmiotow/uzasadnienie-stosowania-wymagan',
            ],
          },
          {
            type: 'category',
            label: 'Procesy i schematy',
            link: {
              type: 'doc',
              id: 'komunikacja/tresci-od-innych-podmiotow/schematy-index',
            },
            items: [
              'komunikacja/tresci-od-innych-podmiotow/proces-publikacji',
              'komunikacja/tresci-od-innych-podmiotow/proces-uproszczony',
              'komunikacja/tresci-od-innych-podmiotow/decyzja-publikacyjna',
            ],
          },
          {
            type: 'category',
            label: 'Narzędzia i załączniki',
            link: {
              type: 'doc',
              id: 'komunikacja/tresci-od-innych-podmiotow/zalaczniki-index',
            },
            items: [
              'komunikacja/tresci-od-innych-podmiotow/formularz-przekazania-materialu',
              'komunikacja/tresci-od-innych-podmiotow/schemat-klasyfikacji-tresci',
              'komunikacja/tresci-od-innych-podmiotow/lista-kontrolna-przed-publikacja',
              'komunikacja/tresci-od-innych-podmiotow/wzor-odmowy-publikacji',
              'komunikacja/tresci-od-innych-podmiotow/wzor-informacji-o-brakach',
              'komunikacja/tresci-od-innych-podmiotow/oznaczenie-tresci-obowiazkowej',
              'komunikacja/tresci-od-innych-podmiotow/oznaczenie-tresci-wylaczonej',
              'komunikacja/tresci-od-innych-podmiotow/instrukcja-dla-podmiotow-zewnetrznych',
            ],
          },
          {
            type: 'category',
            label: 'Kontekst',
            link: {
              type: 'doc',
              id: 'komunikacja/tresci-od-innych-podmiotow/kontekst-index',
            },
            items: [
              'komunikacja/tresci-od-innych-podmiotow/problem-i-kontekst',
              'komunikacja/tresci-od-innych-podmiotow/problemy-i-bledy-wdrozeniowe',
              'komunikacja/tresci-od-innych-podmiotow/zasady-projektowe',
              'komunikacja/tresci-od-innych-podmiotow/powiazania-systemowe',
              'komunikacja/tresci-od-innych-podmiotow/efekty-wdrozenia',
            ],
          },
        ],
      },
      { type: 'autogenerated', dirName: 'komunikacja/komunikacja-bezposrednia' },
    ],
    cykltikSidebar: [{ type: 'autogenerated', dirName: 'cykltik' }],
    wiedzaSidebar: [{ type: 'autogenerated', dirName: 'wiedza' }],
    kulturaSidebar: [{ type: 'autogenerated', dirName: 'kultura' }],
    pracownicySidebar: [{ type: 'autogenerated', dirName: 'pracownicy' }],
    zaopatrzenieSidebar: [{ type: 'autogenerated', dirName: 'zaopatrzenie' }],
    wsparcieSidebar: [{ type: 'autogenerated', dirName: 'wsparcie' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
