import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

    osieciSidebar: [{ type: 'autogenerated', dirName: 'o-sieci' }],
    komunikacjaSidebar: [
      { type: 'autogenerated', dirName: 'komunikacja/wymiar-komunikacja' },
      { type: 'autogenerated', dirName: 'komunikacja/dostepne-dokumenty' },
      { type: 'autogenerated', dirName: 'komunikacja/komunikacja-bezposrednia' },
      {
        type: 'category',
        label: 'Komunikacja masowa',
        link: { type: 'generated-index' },
        items: [
          'komunikacja/komunikacja-masowa/komunikacja-masowa',
          'komunikacja/komunikacja-masowa/wymagania-index',
          'komunikacja/komunikacja-masowa/minimalne-wymagania',
          'komunikacja/komunikacja-masowa/uzasadnienie-stosowania',
          'komunikacja/komunikacja-masowa/standardy-tworzenia-index',
          'komunikacja/komunikacja-masowa/01-standard-tworzenia-dostepnych-materialow-wideo',
          'komunikacja/komunikacja-masowa/02-standard-tworzenia-dostepnych-grafik-i-materialow-wizualnych',
          'komunikacja/komunikacja-masowa/03-standard-opisu-alternatywnego-i-tresci-rownowaznych',
          'komunikacja/komunikacja-masowa/04-standard-struktury-komunikatu-i-tworzenia-tresci',
          'komunikacja/komunikacja-masowa/05-standard-tworzenia-dostepnych-materialow-audio',
        ],
      },
    ],
    cykltikSidebar: [{ type: 'autogenerated', dirName: 'cykltik' }],
    wiedzaSidebar: [{ type: 'autogenerated', dirName: 'wiedza' }],
    kulturaSidebar: [{ type: 'autogenerated', dirName: 'kultura' }],
    pracownicySidebar: [{ type: 'autogenerated', dirName: 'pracownicy' }],
    zaopatrzenieSidebar: [{ type: 'autogenerated', dirName: 'zaopatrzenie' }],
    wsparcieSidebar: [{ type: 'autogenerated', dirName: 'wsparcie' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
