name: Block Merge Without Required Review

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]
jobs:
  require-one-review:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure at least one required reviewer approved
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredReviewers = ["zwiastunsw", "redaktorbs", "MKW2017"]; // <-- replace with usernames
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            // Map latest review state per user
            const latest = {};
            reviews.forEach(r => { latest[r.user.login] = r.state; });

            // Check if none of the required reviewers approved
            const hasApproval = requiredReviewers.some(u => latest[u] === "APPROVED");

            if (!hasApproval) {
              core.setFailed(
                `❌ Pull request blocked: At least one of the required reviewers must approve. Required: ${requiredReviewers.join(", ")}`
              );
            } else {
              console.log("✅ Merge allowed: At least one required reviewer approved");
            }
