name: PR Labeler
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
permissions:
  contents: read
  pull-requests: write
 
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Zastosuj etykiety w oparciu o ścieżkę pliku
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml