name: Test deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches: [test-linkow]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: documentation
        run: npm install -f

      - name: Build site
        working-directory: documentation
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: documentation/build
